
* In:
/data/oceanparcels/output_data/data_LauraGN/outputs_parcels/WOC/Sargassum/20180312065959-WOC-L4-CURlag-TATL_sargassum_drift_1H_15m_drifters_180days-v1.0-fv1.0.nc

* outname:
/data/oceanparcels/output_data/data_LauraGN/outputs_parcels/WOC/Sargassum/20180312070000-WOC-L4-CURlag_15m-TATL_SARGASSUM_DRIFT_1H_DRIFTERS-v1.0-fv2.0.nc



In [1]:
!rm /data/oceanparcels/output_data/data_LauraGN/outputs_parcels/WOC/Sargassum/20180312070000-WOC-L4-CURlag_15m-TATL_SARGASSUM_DRIFT_1H_DRIFTERS-v1.0-fv2.0.nc

rm: cannot remove '/data/oceanparcels/output_data/data_LauraGN/outputs_parcels/WOC/Sargassum/20180312070000-WOC-L4-CURlag_15m-TATL_SARGASSUM_DRIFT_1H_DRIFTERS-v1.0-fv2.0.nc': No such file or directory


In [2]:
!rm /data/oceanparcels/output_data/data_LauraGN/outputs_parcels/WOC/Sargassum/out_*

rm: cannot remove '/data/oceanparcels/output_data/data_LauraGN/outputs_parcels/WOC/Sargassum/out_*': No such file or directory


# 1. Changing reference time:

In [3]:
!ncap2 -h -s 'time=udunits(time, "seconds since 1970-01-01");time@units="seconds since 1970-01-01"' /data/oceanparcels/output_data/data_LauraGN/outputs_parcels/WOC/Sargassum/20180312065959-WOC-L4-CURlag-TATL_sargassum_drift_1H_15m_drifters_180days-v1.0-fv1.0.nc /data/oceanparcels/output_data/data_LauraGN/outputs_parcels/WOC/Sargassum/out_01.nc

In [4]:
!ncdump -h /data/oceanparcels/output_data/data_LauraGN/outputs_parcels/WOC/Sargassum/out_01.nc

netcdf out_01 {
dimensions:
	traj = 10 ;
	obs = 4322 ;
variables:
	double time(traj, obs) ;
		time:_FillValue = NaN ;
		time:axis = "T" ;
		time:calendar = "standard" ;
		time:long_name = "" ;
		time:standard_name = "time" ;
		time:units = "seconds since 1970-01-01" ;
	int64 trajectory(traj, obs) ;
		trajectory:_FillValue = -9223372036854775808L ;
		trajectory:long_name = "Unique identifier for each particle" ;
		trajectory:cf_role = "trajectory_id" ;
	float lat(traj, obs) ;
		lat:_FillValue = NaNf ;
		lat:long_name = "" ;
		lat:standard_name = "latitude" ;
		lat:units = "degrees_north" ;
		lat:axis = "Y" ;
	float lon(traj, obs) ;
		lon:_FillValue = NaNf ;
		lon:long_name = "" ;
		lon:standard_name = "longitude" ;
		lon:units = "degrees_east" ;
		lon:axis = "X" ;
	float z(traj, obs) ;
		z:_FillValue = NaNf ;
		z:long_name = "" ;
		z:standard_name = "depth" ;
		z:units = "m" ;
		z:positive = "down" ;
	float age(traj, obs) ;
		age:_FillValue = NaNf ;
		age:long_name = "" ;
		age:standard

# 2. Modifying trajectory:

In [5]:
import xarray as xr
import numpy as np

In [6]:
ds = xr.open_dataset('/data/oceanparcels/output_data/data_LauraGN/outputs_parcels/WOC/Sargassum/out_01.nc')

In [7]:
ds

<xarray.Dataset>
Dimensions:     (obs: 4322, traj: 10)
Dimensions without coordinates: obs, traj
Data variables:
    time        (traj, obs) datetime64[ns] ...
    trajectory  (traj, obs) float64 ...
    lat         (traj, obs) float32 ...
    lon         (traj, obs) float32 ...
    z           (traj, obs) float32 ...
    age         (traj, obs) float32 ...
    launch_id   (traj) float32 ...
Attributes:
    feature_type:                  trajectory
    Conventions:                   CF-1.7, ACDD-1.3, ISO 8601
    ncei_template_version:         NCEI_NetCDF_Trajectory_Template_v2.0
    parcels_version:               2.2.2.dev126+g6dd05b7
    parcels_mesh:                  spherical
    Metadata_Conventions:          Climate and Forecast (CF) 1.7, Attribute C...
    standard_name_vocabulary:      NetCDF Climate and Forecast (CF) Metadata ...
    title:                         Tropical Atlantic 2D horizontal drift of S...
    summary:                       This dataset contains the positio

## 2.1 Modifying it so it only depends on itself:

In [8]:
ds.trajectory[:,0]

<xarray.DataArray 'trajectory' (traj: 10)>
array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
Dimensions without coordinates: traj
Attributes:
    long_name:  Unique identifier for each particle
    cf_role:    trajectory_id

In [9]:
ds['trajectory'] = ds.trajectory[:,0]

## 2.2 Renaming traj to trajectory:

In [10]:
ds = ds.rename({'traj':'trajectory'}) 

In [11]:
ds

<xarray.Dataset>
Dimensions:     (obs: 4322, trajectory: 10)
Dimensions without coordinates: obs, trajectory
Data variables:
    time        (trajectory, obs) datetime64[ns] ...
    trajectory  (trajectory) float64 ...
    lat         (trajectory, obs) float32 ...
    lon         (trajectory, obs) float32 ...
    z           (trajectory, obs) float32 ...
    age         (trajectory, obs) float32 ...
    launch_id   (trajectory) float32 ...
Attributes:
    feature_type:                  trajectory
    Conventions:                   CF-1.7, ACDD-1.3, ISO 8601
    ncei_template_version:         NCEI_NetCDF_Trajectory_Template_v2.0
    parcels_version:               2.2.2.dev126+g6dd05b7
    parcels_mesh:                  spherical
    Metadata_Conventions:          Climate and Forecast (CF) 1.7, Attribute C...
    standard_name_vocabulary:      NetCDF Climate and Forecast (CF) Metadata ...
    title:                         Tropical Atlantic 2D horizontal drift of S...
    summary:       

In [12]:
ds.to_netcdf('/data/oceanparcels/output_data/data_LauraGN/outputs_parcels/WOC/Sargassum/out_02.nc')

In [13]:
!ncdump -h /data/oceanparcels/output_data/data_LauraGN/outputs_parcels/WOC/Sargassum/out_02.nc

netcdf out_02 {
dimensions:
	trajectory = 10 ;
	obs = 4322 ;
variables:
	double time(trajectory, obs) ;
		time:_FillValue = NaN ;
		time:axis = "T" ;
		time:long_name = "" ;
		time:standard_name = "time" ;
		time:units = "seconds since 1970-01-01" ;
		time:calendar = "standard" ;
	int64 trajectory(trajectory) ;
		trajectory:_FillValue = -9223372036854775808L ;
		trajectory:long_name = "Unique identifier for each particle" ;
		trajectory:cf_role = "trajectory_id" ;
	float lat(trajectory, obs) ;
		lat:_FillValue = NaNf ;
		lat:long_name = "" ;
		lat:standard_name = "latitude" ;
		lat:units = "degrees_north" ;
		lat:axis = "Y" ;
	float lon(trajectory, obs) ;
		lon:_FillValue = NaNf ;
		lon:long_name = "" ;
		lon:standard_name = "longitude" ;
		lon:units = "degrees_east" ;
		lon:axis = "X" ;
	float z(trajectory, obs) ;
		z:_FillValue = NaNf ;
		z:long_name = "" ;
		z:standard_name = "depth" ;
		z:units = "m" ;
		z:positive = "down" ;
	float age(trajectory, obs) ;
		age:_FillValue = NaNf ;


# 3. Change NaN values to 1e20:

In [14]:
!ncatted -h -a _FillValue,,m,f,1.0e20 /data/oceanparcels/output_data/data_LauraGN/outputs_parcels/WOC/Sargassum/out_02.nc

In [15]:
!ncdump -h /data/oceanparcels/output_data/data_LauraGN/outputs_parcels/WOC/Sargassum/out_02.nc

netcdf out_02 {
dimensions:
	trajectory = 10 ;
	obs = 4322 ;
variables:
	double time(trajectory, obs) ;
		time:axis = "T" ;
		time:long_name = "" ;
		time:standard_name = "time" ;
		time:units = "seconds since 1970-01-01" ;
		time:calendar = "standard" ;
		time:_FillValue = 1.e+20f ;
	int64 trajectory(trajectory) ;
		trajectory:long_name = "Unique identifier for each particle" ;
		trajectory:cf_role = "trajectory_id" ;
		trajectory:_FillValue = 1.e+20f ;
	float lat(trajectory, obs) ;
		lat:long_name = "" ;
		lat:standard_name = "latitude" ;
		lat:units = "degrees_north" ;
		lat:axis = "Y" ;
		lat:_FillValue = 1.e+20f ;
	float lon(trajectory, obs) ;
		lon:long_name = "" ;
		lon:standard_name = "longitude" ;
		lon:units = "degrees_east" ;
		lon:axis = "X" ;
		lon:_FillValue = 1.e+20f ;
	float z(trajectory, obs) ;
		z:long_name = "" ;
		z:standard_name = "depth" ;
		z:units = "m" ;
		z:positive = "down" ;
		z:_FillValue = 1.e+20f ;
	float age(trajectory, obs) ;
		age:long_name = "" ;
		ag

# 4. Rename:

adding depth and fv02 to filename

In [16]:
!mv /data/oceanparcels/output_data/data_LauraGN/outputs_parcels/WOC/Sargassum/out_02.nc /data/oceanparcels/output_data/data_LauraGN/outputs_parcels/WOC/Sargassum/20180312070000-WOC-L4-CURlag_15m-TATL_SARGASSUM_DRIFT_1H_DRIFTERS-v1.0-fv2.0.nc

In [17]:
!ncdump -h /data/oceanparcels/output_data/data_LauraGN/outputs_parcels/WOC/Sargassum/20180312070000-WOC-L4-CURlag_15m-TATL_SARGASSUM_DRIFT_1H_DRIFTERS-v1.0-fv2.0.nc

netcdf \20180312070000-WOC-L4-CURlag_15m-TATL_SARGASSUM_DRIFT_1H_DRIFTERS-v1.0-fv2.0 {
dimensions:
	trajectory = 10 ;
	obs = 4322 ;
variables:
	double time(trajectory, obs) ;
		time:axis = "T" ;
		time:long_name = "" ;
		time:standard_name = "time" ;
		time:units = "seconds since 1970-01-01" ;
		time:calendar = "standard" ;
		time:_FillValue = 1.e+20f ;
	int64 trajectory(trajectory) ;
		trajectory:long_name = "Unique identifier for each particle" ;
		trajectory:cf_role = "trajectory_id" ;
		trajectory:_FillValue = 1.e+20f ;
	float lat(trajectory, obs) ;
		lat:long_name = "" ;
		lat:standard_name = "latitude" ;
		lat:units = "degrees_north" ;
		lat:axis = "Y" ;
		lat:_FillValue = 1.e+20f ;
	float lon(trajectory, obs) ;
		lon:long_name = "" ;
		lon:standard_name = "longitude" ;
		lon:units = "degrees_east" ;
		lon:axis = "X" ;
		lon:_FillValue = 1.e+20f ;
	float z(trajectory, obs) ;
		z:long_name = "" ;
		z:standard_name = "depth" ;
		z:units = "m" ;
		z:positive = "down" ;
		z:_FillValu

# 6. Delete extra files

In [18]:
!rm -rf /data/oceanparcels/output_data/data_LauraGN/outputs_parcels/WOC/Sargassum/out_*

# 7. Opening with xarray

In [19]:
ds = xr.open_dataset('/data/oceanparcels/output_data/data_LauraGN/outputs_parcels/WOC/Sargassum/20180312070000-WOC-L4-CURlag_15m-TATL_SARGASSUM_DRIFT_1H_DRIFTERS-v1.0-fv2.0.nc')

In [20]:
ds

<xarray.Dataset>
Dimensions:     (obs: 4322, trajectory: 10)
Coordinates:
  * trajectory  (trajectory) float64 0.0 1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0 9.0
Dimensions without coordinates: obs
Data variables:
    time        (trajectory, obs) datetime64[ns] ...
    lat         (trajectory, obs) float32 ...
    lon         (trajectory, obs) float32 ...
    z           (trajectory, obs) float32 ...
    age         (trajectory, obs) float32 ...
    launch_id   (trajectory) float32 ...
Attributes:
    feature_type:                  trajectory
    Conventions:                   CF-1.7, ACDD-1.3, ISO 8601
    ncei_template_version:         NCEI_NetCDF_Trajectory_Template_v2.0
    parcels_version:               2.2.2.dev126+g6dd05b7
    parcels_mesh:                  spherical
    Metadata_Conventions:          Climate and Forecast (CF) 1.7, Attribute C...
    standard_name_vocabulary:      NetCDF Climate and Forecast (CF) Metadata ...
    title:                         Tropical Atlantic 2D horizon

In [21]:
ds.trajectory

<xarray.DataArray 'trajectory' (trajectory: 10)>
array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
Coordinates:
  * trajectory  (trajectory) float64 0.0 1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0 9.0
Attributes:
    long_name:  Unique identifier for each particle
    cf_role:    trajectory_id

In [22]:
ds.lon

<xarray.DataArray 'lon' (trajectory: 10, obs: 4322)>
array([[-61.71927 , -61.71557 , -61.711987, ..., -60.903778, -60.903034,
        -60.902905],
       [-61.71469 , -61.711094, -61.70755 , ..., -60.634727, -60.63163 ,
        -60.63137 ],
       [-61.720455, -61.71674 , -61.71314 , ..., -60.8891  , -60.88854 ,
               nan],
       ...,
       [-46.05394 , -46.055523, -46.0568  , ...,        nan,        nan,
               nan],
       [-46.009   , -46.011196, -46.013653, ...,        nan,        nan,
               nan],
       [-46.003   , -46.00606 , -46.00913 , ...,        nan,        nan,
               nan]], dtype=float32)
Coordinates:
  * trajectory  (trajectory) float64 0.0 1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0 9.0
Dimensions without coordinates: obs
Attributes:
    long_name:      
    standard_name:  longitude
    units:          degrees_east
    axis:           X